new changes to playblast ui and ffmpeg
NLA1995/playblast-project pull request #13
Opened 2024-09-22 21:51 UTC by NLA1995

Please review the new function validate, inside the class IntegerValidator, the new arrangement of button browse, and the conditions of the frame range, frame rate, and size fields.

2024-09-24 05:37 UTC, agetroortega requested changes
Muy bien en general! Me gusto lo de la validacion y el boton que resetea la informacion.

Te deje algunos comentarios, por eso aun no lo he aprobado, y viendo tu UI tengo otras 2 cosas que ayudarian:

- Pon el "Export directory" abajo de la linea del nombre del playblast ya que estan relacionadas.
- Falta hacer validacion de la carpeta a donde exportar, necesitamos asegurarnos de que exista antes de hacer el playblast.
- Tambien validar que hay un nombre de playblast, que el line edit no este vacio.

Una forma mas eficiente de hacerlo es crear una funcion que se encargue de validar todos tus datos, y dentro de la funcion que hace el playblast llamar a esa nueva funcion para validar los datos, si algo no es valido le muestras un error al usuario y no corres el playblast. Si tienes tiempo intenta hacerlo de esta forma, si no puede ser para la siguiente ronda.

2024-09-24 05:37 UTC, agetroortega commented on src/core/capture.py
> +        company_name = ""
Esta funcion que esta haciendo?

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +class IntegerValidator(QValidator):
Muy bien!!

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        """
```suggestion
        Args:
             parent (QWidget): Parent widget for the window. Default to Maya window.
            debug (bool): Initialize in debug mode. If True, the temporary folder will not be deleted.
        """
```

No te olvides del "type" de cada argumento. Te puse un ejemplo de como describiria yo estos argumentos, no queremos que sean muy especificos ya que son relativamente genericos, por ejemplo el "parent" puede ser algo que no sea necesariamente la ventana de Maya.

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        self.rate_line_edit.addItem("60")
Me gusta la idea de usar un combobox, pero podrias agregar los items con un for loop en vez de linea por linea.

Y tambien cambia el nombre de la variable, por que ya no es un line edit.

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        self.height_line_edit.setValidator(IntegerValidator())
Me gusto mucho como estas validando esto ⭐

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        start = start.split('.')[0]
La funcion `cmds.playbackOptions` te esta dando un float, entonces puedes simplemente hacerlo un int y luego un string, por ejemplo:

```python
start = int(cmds.playbackOptions(q=True, min=True))
start = str(start)
```

No es necesario hacer el split.

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        self.browse_button.setIcon(QIcon(ICON))
Hazle un print a `ICON` y asegurate de que el path que te esta dando sea correcto.

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        This function cleans the fields of the ui
```suggestion
        This function resets the fields of the ui
```

2024-09-24 05:37 UTC, agetroortega commented on src/ui/playblast_ui.py
> +        self.playblast_mgr.do_clean(dir_name, file_name, width, height, start_frame, end_frame, artist_name, department_name, company_name)
Esta muy bien esta funcion de clean, solo no entiendo por que necesitas esta otra en el playblast manager.

2024-09-24 05:37 UTC, agetroortega commented on src/utils/ffmpeg_utils.py
> +def run_subprocess(command):
No olvides el docstring

2024-09-24 05:37 UTC, agetroortega commented on src/utils/ffmpeg_utils.py
> +def add_fcount_overlay(input_video_path, output_video_path, start_frame):
Yo le pondria un nombre mas claro, como `add_current_frame_overlay`, tambien por que "frame count" se refiere al numero de frames en el video, pero esta funcion es para agregar el numero del frame actual.

Y no olvides el docstring.

2024-09-24 05:37 UTC, agetroortega commented on src/utils/ffmpeg_utils.py
> +        f"drawtext=fontfile='C\\:/Windows/Fonts/Arial.ttf':"
Acuerdate que solamente escribir "Arial" es suficiente.

2024-09-24 05:37 UTC, agetroortega commented on src/utils/playblast_utils.py
> +    print("this is the before", before_part)
Este print no es necesario, o si?

2024-09-25 22:05 UTC, NLA1995 commented on src/core/capture.py
> +        company_name = ""
Existir para poderla llamar adentro de playblast_ui, pero creo que con un pass daria el mismo resultado no?

2024-09-25 22:53 UTC, NLA1995 commented on src/utils/playblast_utils.py
> +    print("this is the before", before_part)
estaba haciendo pruebas

2024-09-28 17:50 UTC, agetroortega approved these changes
🚀

2024-09-28 17:51 UTC, merged